import express from "express";
import usuarioService from "../services/usuarioService.js";
import usuarioRepository from "../repositories/usuarioRepository.js";
import autorizacionService from "../services/autorizacionService.js";
import { Permiso, Rol } from "../models/seguridad.js";
import { HistorialAcceso } from "../models/seguridad.js";
import { verificarPermiso } from "../middleware/autenticacion.js";

const router = express.Router();
const contexto = (req) => ({ ip: req.ip, dispositivo: req.get("user-agent") });
const puedeAdministrarAccesos = (req) => req.usuario.roles?.some((rol) => ["owner", "administrador"].includes(rol));
const esOwner = (req) => req.usuario.roles?.includes("owner");
const puedeAsignarRol = (req, rol) => esOwner(req) || rol !== "owner";

router.get("/", verificarPermiso("usuarios.gestionar"), async (req, res) => { const usuarios = await usuarioRepository.buscar({}, {}, req.usuario.restauranteId); const salida = await Promise.all(usuarios.map(async (usuario) => usuarioService.serializarUsuario(usuario, await autorizacionService.obtenerContexto(usuario)))); res.json(salida); });
router.post("/", verificarPermiso("usuarios.gestionar"), async (req, res) => { try { if (!puedeAdministrarAccesos(req)) return res.status(403).json({ error: "Solo owner o administrador pueden crear usuarios" }); if (!puedeAsignarRol(req, req.body.rol)) return res.status(403).json({ error: "Solo owner puede crear otro owner" }); res.status(201).json(await usuarioService.crearUsuario(req.usuarioModelo, req.body, contexto(req))); } catch (err) { res.status(400).json({ error: err.message }); } });
router.patch("/:id/rol", verificarPermiso("usuarios.gestionar"), async (req, res) => { try { if (!puedeAdministrarAccesos(req)) return res.status(403).json({ error: "Solo owner o administrador pueden cambiar roles" }); const usuario = await usuarioRepository.obtenerPorId(Number(req.params.id), req.usuario.restauranteId); if (!usuario) return res.status(404).json({ error: "Usuario no encontrado" }); if (!puedeAsignarRol(req, req.body.rol) || (usuario.roles === "owner" && !esOwner(req))) return res.status(403).json({ error: "Solo owner puede administrar cuentas owner" }); const rol = await autorizacionService.asignarRol(usuario.id, req.usuario.restauranteId, req.body.rol); await usuario.update({ roles: rol.clave }); res.json({ mensaje: "Rol actualizado" }); } catch (err) { res.status(400).json({ error: err.message }); } });
router.patch("/:id/activo", verificarPermiso("usuarios.gestionar"), async (req, res) => { if (!puedeAdministrarAccesos(req)) return res.status(403).json({ error: "Solo owner o administrador pueden cambiar estados" }); const usuario = await usuarioRepository.obtenerPorId(Number(req.params.id), req.usuario.restauranteId); if (!usuario) return res.status(404).json({ error: "Usuario no encontrado" }); if ((usuario.id === req.usuario.id || (usuario.roles === "owner" && !esOwner(req))) && req.body.activo === false) return res.status(400).json({ error: "No podés desactivar esta cuenta" }); await usuario.update({ activo: Boolean(req.body.activo) }); res.json({ mensaje: "Estado actualizado" }); });
router.get("/:id/sesiones", verificarPermiso("usuarios.gestionar"), async (req, res) => { const usuario = await usuarioRepository.obtenerPorId(Number(req.params.id), req.usuario.restauranteId); if (!usuario) return res.status(404).json({ error: "Usuario no encontrado" }); res.json(await usuarioService.sesiones(usuario.id)); });
router.get("/:id/historial", verificarPermiso("usuarios.gestionar"), async (req, res) => { const usuario = await usuarioRepository.obtenerPorId(Number(req.params.id), req.usuario.restauranteId); if (!usuario) return res.status(404).json({ error: "Usuario no encontrado" }); res.json(await HistorialAcceso.findAll({ where: { usuarioId: usuario.id, restauranteId: req.usuario.restauranteId }, order: [["createdAt", "DESC"]], limit: Math.min(Number(req.query.limite) || 50, 200) })); });
router.delete("/sesiones/:id", verificarPermiso("usuarios.gestionar"), async (req, res) => { try { const sesion = await (await import("../models/seguridad.js")).SesionUsuario.findByPk(req.params.id); if (!sesion) return res.status(404).json({ error: "Sesión no encontrada" }); const usuario = await usuarioRepository.obtenerPorId(sesion.usuarioId, req.usuario.restauranteId); if (!usuario) return res.status(404).json({ error: "Sesión no encontrada" }); await usuarioService.revocarSesion(usuario, sesion.id, contexto(req)); res.status(204).end(); } catch (err) { res.status(400).json({ error: err.message }); } });
router.get("/config/roles", verificarPermiso("usuarios.gestionar"), async (req, res) => { await autorizacionService.asegurarCatalogo(req.usuario.restauranteId); res.json({ roles: await Rol.findAll({ where: { restauranteId: req.usuario.restauranteId }, include: [{ model: Permiso, as: "permisos", through: { attributes: [] } }] }), permisos: await Permiso.findAll() }); });
router.post("/config/roles", verificarPermiso("usuarios.gestionar"), async (req, res) => { try { const clave = String(req.body.clave || "").trim().toLowerCase().replace(/[^a-z0-9_]/g, "_"); if (!clave || !req.body.nombre) throw new Error("Nombre y clave de rol son requeridos"); const rol = await Rol.create({ restauranteId: req.usuario.restauranteId, clave, nombre: req.body.nombre }); const permisos = await Permiso.findAll({ where: { clave: req.body.permisos || [] } }); await rol.setPermisos(permisos); res.status(201).json(rol); } catch (err) { res.status(400).json({ error: err.message }); } });
router.put("/config/roles/:id", verificarPermiso("usuarios.gestionar"), async (req, res) => { try { const rol = await Rol.findOne({ where: { id: Number(req.params.id), restauranteId: req.usuario.restauranteId } }); if (!rol) return res.status(404).json({ error: "Rol no encontrado" }); if (rol.esSistema && !["owner", "administrador"].includes(req.usuario.roles?.[0])) return res.status(403).json({ error: "No podés editar un rol de sistema" }); await rol.update({ nombre: req.body.nombre || rol.nombre }); const permisos = await Permiso.findAll({ where: { clave: req.body.permisos || [] } }); await rol.setPermisos(permisos); res.json(rol); } catch (err) { res.status(400).json({ error: err.message }); } });

export default router;
